### ISSUE TITLE
Directory does not exist

### ISSUE THREAD

**Issue by Zeioth** [dhruvasagar/vim-prosession#70] opened 2020-07-08 00:24 UTC
Let's say I have a session ".vim/sessions/meta.vim"

    :Prosession meta

Autocomplete correctly, but when I press enter, I get the error:

    Directory meta does not exist

To fix this I have to create the directory "~/meta"

The thing is I don't wanna have "~/meta" I want to have ~/activities/meta. There's some way to bypass the checking to achieve this? Thank you

**Comment by Zeioth** [comment] 2020-07-08 01:08
Deleting this block from prosession.vim fixes the issue. It seems that 'throw' is preventing prosession from opening the session unless I put the directory on "~/"

    if !isdirectory(dir)
      call s:throw('Directory ' . dir . ' does not exist')
    endif

**Comment by dhruvasagar** [comment] 2020-07-08 01:27
@Zeioth If you want to load a session manually, you might as well source it manually. Prosession follows a naming convention for the session files. Can you elaborate on exactly what you want to achieve ?

**Comment by Zeioth** [comment] 2020-07-08 12:48
The issue I was experiencing was that I could not open a session unless there was a directory with the same name as my session in "~/". IDk if was a missconfiguration issue, or a bug.

**Comment by dhruvasagar** [comment] 2024-03-07 06:23
Prosession doesn't really require or do anything special with `~/` directory. I am closing this since I am not able to reproduce this.

**Closed by dhruvasagar** 2024-03-07 06:23 UTC
