### ISSUE TITLE
Prosession seems to break ability to save tabs as part of the session

### ISSUE THREAD

**Issue by TC72** [dhruvasagar/vim-prosession#60] opened 2018-12-09 15:42 UTC
Not sure if I'm doing this wrong but if I have 2 tabs open, one of them used lcd so both tabs have different directories as their current directory. When I quit vim with :qa prosession creates 2 session files 1 for each tab.

If I do the same thing without prosession, obsession saves the tabs as part of my current Session.vim file. If I open vim with vim -s Session.vim I get both my tabs back and they are both using the correct directory.

I've read that some people like the idea of creating separate session files for each tab. That would be fine but the behaviour of prosession if I try to switch session in the second tab is to put me into a session with only 1 tab.

**Comment by dhruvasagar** [comment] 2019-06-19 16:08
@TC72 I am not able to reproduce this issue, I am successfully able to open multiple tabs, use `:lcd` and then when I use `:qa` to exit and relaunch vim, prosession is able to get back to both tabs as before closing with their own separate directories.

**Closed by dhruvasagar** 2019-06-19 16:08 UTC
